version: "3.5"
services:
  app:
    image: suecharo/sapporo-web:1.0.1
    container_name: sapporo-web
    environment:
      - NUXT_HOST=0.0.0.0
      - NUXT_PORT=1121
    ports:
      - 1121:1121
    restart: always
    working_dir: /app
    command: ["yarn", "start"]
    networks:
      - sapporo

networks:
  sapporo:
    name: sapporo-network
