version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sapporo-web
    volumes:
      - ${PWD}:/app
      - /app/node_modules
    environment:
      - NUXT_HOST=0.0.0.0
      - NUXT_PORT=1121
      # - SAPPORO_URL_PREFIX=/prefix/
      # - SAPPORO_LOAD_PRE_REGISTERED_SERVICES=true # true or false
    ports:
      - 0.0.0.0:1121:1121
    restart: on-failure
    command: ['sleep', 'infinity']
