version: "3.5"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile-dev
    image: sapporo-web-dev
    container_name: sapporo-web-dev
    volumes:
      - ${PWD}:/app
      - /app/node_modules
    environment:
      - NUXT_HOST=0.0.0.0
      - NUXT_PORT=1121
      # - SAPPORO_URL_PREFIX=/prefix/
      # - SAPPORO_LOAD_PRE_REGISTERED_SERVICES=true # true or false
    ports:
      - 0.0.0.0:1121:1121
    restart: on-failure
    working_dir: /app
    command: ["sleep", "infinity"]
    networks:
      - sapporo

networks:
  sapporo:
    name: sapporo-network
