name: deploy_github_pages

on:
  release:
    types:
      - published
  workflow_dispatch: {}

jobs:
  deploy_github_pages:
    if: github.repository == 'ddbj/sapporo-web'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '15'
      - name: Install dependencies
        run: yarn install
      - name: Generate
        run: SAPPORO_URL_PREFIX=/sapporo-web/ yarn generate
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: gh-pages
