name: deploy_github_pages

on:
  release:
    types:
      - published

jobs:
  deploy_github_pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '15'
      - name: Install dependencies
        run: yarn install
      - name: Build and publish
        run: yarn deploy
